#      _____              __          
#    _/ ____\____   _____/  |_  ______
#    \   __\/  _ \ /    \   __\/  ___/
#     |  | (  <_> )   |  \  |  \___ \ 
#     |__|  \____/|___|  /__| /____  >
#                      \/          \/ 



[font]

normal = { family = "CaskaydiaCove Nerd Font Mono", style="Regular" }
