





general.import = [
	#Theme
	"~/.config/alacritty/00-catpuccin-macchiato.toml",
	"~/.config/alacritty/01-window.toml",
	"~/.config/alacritty/02-keybindings.toml",
	"~/.config/alacritty/03-font.toml"
]
