#    ________                      .__  __          
#    \_____  \ ___________    ____ |__|/  |_ ___.__.
#     /   |   \\____ \__  \ _/ ___\|  \   __<   |  |
#    /    |    \  |_> > __ \\  \___|  ||  |  \___  |
#    \_______  /   __(____  /\___  >__||__|  / ____|
#            \/|__|       \/     \/          \/     

# Opacity of window titlebars and borders.
#
# Range: 0.1 - 1.0
# Default: 1.0 (disabled)
frame-opacity = 0.9;


rules: ({
	match = "class_g = !focused";
	opacity = 0.5;
}, {
	match = "class_g = 'Alacritty' && focused";
	opacity = 0.8;
})