#    __________      .__                 
#    \______   \__ __|  |   ____   ______
#     |       _/  |  \  | _/ __ \ /  ___/
#     |    |   \  |  /  |_\  ___/ \___ \ 
#     |____|_  /____/|____/\___  >____  >
#            \/                \/     \/ 

rules: ({
    match = "!focused";
	opacity = 0.95;
}, {
    match = "class_g = 'Alacritty' && !focused";
    opacity = 0.65; 
}, {
    match = "class_g = 'Alacritty' && focused";
	opacity = 0.85;
}, {
    match = "fullscreen";
    	opacity = 1.0;
	corner-radius = 0;
	round-borders = 0;
	shadow = false;
})

