#    __________      .__                 
#    \______   \__ __|  |   ____   ______
#     |       _/  |  \  | _/ __ \ /  ___/
#     |    |   \  |  /  |_\  ___/ \___ \ 
#     |____|_  /____/|____/\___  >____  >
#            \/                \/     \/ 

rules: ({
    match = "!focused";
	opacity = 0.7;
}, {
    match = "class_g = 'Alacritty' && focused";
	opacity = 0.8;
})