#      _________.__                .___             
#     /   _____/|  |__ _____     __| _/______  _  __
#     \_____  \ |  |  \\__  \   / __ |/  _ \ \/ \/ /
#     /        \|   Y  \/ __ \_/ /_/ (  <_> )     / 
#    /_______  /|___|  (____  /\____ |\____/ \/\_/  
#            \/      \/     \/      \/              

shadow = true;

shadow-radius = 7;

shadow-offset-x = -7;

shadow-offset-y = -7;