;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   I3 MODULE
;
;
;==========================================================

[module/i3]
type = internal/i3

pin-workspaces = true

show-urgent = true

strip-wsnumbers = true

index-sort = true

enable-click = false

enable-scroll = false

wrapping-scroll = false

reverse-scroll = false

format = <label-state> <label-mode>

label-separator = |
label-separator-padding = 2
label-separator-foreground = ${colors.red}

label-mode = %mode%
label-mode-padding = 2
label-mode-background = ${colors.red}

label-focused = %index%
label-focused-foreground = ${colors.lavender}
label-focused-background = ${colors.overlay1}
label-focused-padding = 2

label-unfocused = %index%
label-unfocused-padding = 2
label-unfocused-foreground = ${colors.lavender}

