;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   I3 MODULE
;
;
;==========================================================

[module/i3]
type = internal/i3

pin-workspaces = true

show-urgent = true

;strip-wsnumbers = true

index-sort = true

enable-click = true

enable-scroll = false

wrapping-scroll = false

reverse-scroll = false

format = <label-state> <label-mode>

label-separator = 
label-separator-padding = 2
label-separator-foreground = ${colors.red}

label-mode = %mode%
label-mode-padding = 2
label-mode-background = ${colors.red}

label-focused = %icon% %name%
label-focused-foreground = ${colors.lavender}
label-focused-background = ${colors.overlay1}
label-focused-padding = 2

label-unfocused = %icon% %name%
label-unfocused-padding = 4
label-unfocused-foreground = ${colors.lavender}
label-unfocused-background = ${colors.overlay1}

label-visible = %icon% %name%
label-visible-padding = 2

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;󰜏
ws-icon-default = 
