;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   BAR BASE
;
;
;==========================================================

[bar/base]

monitor = ${env:MONITOR:}

fixed-center = true

bottom = false

background = ${colors.surface1}
foreground = ${colors.blue}

radius = 0.5

separator = |
separator-padding = 2

dim-value = 0.8

font-0 = CaskaydiaMono Nerd Font Mono,CaskaydiaMono NFM,CaskaydiaMono NFM SemiBold:style=SemiBold,Regular;2

modules-center = name xwindow
modules-right = date
modules-left = i3
