#    ___.                 
#    \_ |__ _____ _______ 
#     | __ \\__  \\_  __ \
#     | \_\ \/ __ \|  | \/
#     |___  (____  /__|   
#         \/     \/       


# Display a bar on the primary output with system status and a systray
bar {
        id bar-0

	status_command i3status -c /home/$USER/.config/i3/i3status.conf

	position top

	tray_output primary

#	output primary

	colors {
		background 	#494d64
		statusline 	#a6da95
		separator 	#a6da95
		active_workspace	#494d64 #494d64 #f0c6c6
		inactive_workspace	#494d64 #494d64 #cad3f5
		focused_workspace	#494d64 #494d64 #f0c6c6
	}
}

# Display a bar on all other output with just the workspace title
#bar {
#	id bar-1
#
#	position top
#
#	output nonprimary
#
#	colors {
#		background	#494d64
#		statusline	#a6da95
#		separator	#a6da95
#		active_workspace	#494d64 #494d64 #f0c6c6
#		inactive_workspace	#494d64 #494d64 #cad3f5
#		focused_workspace	#494d64 #494d64 #f0c6c6
#	}
#}
