#    ___.                 
#    \_ |__ _____ _______ 
#     | __ \\__  \\_  __ \
#     | \_\ \/ __ \|  | \/
#     |___  (____  /__|   
#         \/     \/       


# Display a bar on the primary output with system status and a systray
bar {
        id bar-0

	status_command i3status -c /home/$USER/.config/i3/i3status.conf

	position top

	tray_output primary

	output primary

	colors {
		background 	#8aadf4
		statusline 	#f0c6c6
		separator 	#f0c6c6
		active_workspace	#8aadf4 #8aadf4 #f4dbd6
		inactive_workspace	#8aadf4 #8aadf4 #cad3f5
		focused_workspace	#8aadf4 #8aadf4 #f5a97f
	}
}

# Display a bar on all other output with just the workspace title
bar {
	id bar-1

	position top

	output nonprimary

	colors {
		background	#8aadf4
		statusline	#f0c6c6
		separator	#f0c6c6a
		active_workspace	#8aadf4 #8aadf4 #f4dbd6
		inactive_workspace	#8aadf4 #8aadf4 #cad3f5
		focused_workspace	#8aadf4 #8aadf4 #f5a97f
	}
}
